-- PARTE 2 - 1
la diferencia entre having y where es la manera como se usa :
	el having sirve para filtrar resultado de un conjunto de regitros agrupados.
	el where filtra resultado registro por registro.
	
-- PARTE 2 - 2
CREATE TABLE public.student (
	id int4 Not NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar Not NULL,
	code varchar Not NULL,
	class varchar Not NULL,
	age int Not NULL,
	favorite_subject varchar NULL,
	gpa decimal Not NULL
);

-- PARTE 2 - 3
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('RAMON','00039','sciences',15,'Tecnology',4.2);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ANDRES','00040','social',16,'TV Series',4.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JUAN MANUEL','00041','maths',17,'NBA',4.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('VICENTE','00042','technology',15,'Soccer',4.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('SANTIAGO','00043','sport',12,'Culture',4.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOAQUIN','00044','sciences',13,'News',4.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MARIO','00045','social',14,'Tecnology',4.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('VICTOR','00046','maths',14,'TV Series',4.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('EDUARDO','00047','technology',14,'NBA',4.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ROBERTO','00048','sport',15,'Soccer',4.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JAIME','00049','sciences',16,'Culture',4.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('FRANCISCO JOSE','00050','social',15,'Tecnology',4.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MARCOS','00051','maths',16,'TV Series',4.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('HUGO','00052','technology',17,'NBA',3.3);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('IGNACIO','00053','sport',15,'Soccer',3.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JORDI','00054','sciences',12,'Culture',3.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ALFONSO','00055','social',13,'News',3.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('RICARDO','00056','maths',14,'Tecnology',3.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('SALVADOR','00057','technology',14,'TV Series',3.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('GUILLERMO','00058','sport',14,'NBA',3.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MARC','00059','sciences',15,'Soccer',3.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('GABRIEL','00060','social',16,'Culture',3.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MOHAMED','00061','maths',15,'Tecnology',3.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('EMILIO','00062','technology',16,'TV Series',2.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('GONZALO','00063','sport',17,'NBA',2.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MARTIN','00064','sciences',15,'Soccer',2.2);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE MIGUEL','00065','social',12,'Culture',2.1);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JULIO','00066','maths',13,'News',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JULIAN','00067','technology',14,'Tecnology',2.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('TOMAS','00068','sport',14,'TV Series',2.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('NICOLAS','00069','sciences',14,'NBA',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('AGUSTIN','00070','social',15,'Soccer',2.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE RAMON','00071','maths',16,'Culture',2.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('SAMUEL','00072','technology',15,'News',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ISMAEL','00073','sport',16,'Tecnology',2.8);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('CRISTIAN','00074','sciences',17,'TV Series',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('LUCAS','00075','social',15,'NBA',2.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOAN','00076','maths',12,'Soccer',2.3);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('FELIX','00077','technology',13,'Culture',2.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('AITOR','00078','sport',14,'News',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('HECTOR','00079','sciences',14,'Tecnology',2.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('IKER','00080','social',14,'TV Series',2.8);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ALEX','00081','maths',15,'NBA',2.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JUAN FRANCISCO','00082','technology',16,'Soccer',2.3);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE CARLOS','00083','sport',12,'Culture',1.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSEP','00084','sciences',14,'News',5.0);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('SEBASTIAN','00085','social',16,'Tecnology',1.2);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('CESAR','00086','maths',12,'TV Series',1.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MARIANO','00087','technology',14,'NBA',1.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ALFREDO','00088','sport',16,'Soccer',1.3);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('DOMINGO','00089','sciences',12,'Culture',5.0);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('MATEO','00090','social',14,'News',1.3);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE ANGEL','00091','maths',16,'Tecnology',1.9);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('RODRIGO','00092','technology',17,'TV Series',1.2);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('VICTOR MANUEL','00093','sport',15,'NBA',1.6);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('FELIPE','00094','sciences',12,'Soccer',5.0);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE IGNACIO','00095','social',13,'Culture',1.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('LUIS MIGUEL','00096','maths',14,'News',1.5);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JOSE FRANCISCO','00097','technology',14,'Tecnology',1.4);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('XAVIER','00098','sport',14,'TV Series',5.0);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('JUAN LUIS','00099','sciences',15,'NBA',1.7);
INSERT INTO public.student ("name", code, "class", age, favorite_subject, gpa) VALUES('ALBERT','00100','social',16,'Soccer',1.8);


-- PARTE 2 - 4
select avg(gpa)  as "Average" from public.student s where name like 'A%'

-- PARTE 2 - 5
SELECT id, "name", code, "class", age, favorite_subject, sum(gpa) as "gpa"
	FROM public.student
group by class, "name", code, age, favorite_subject,id
having sum(gpa) > 3.5
order by age, name;